name        : libgnome-menus
version     : 3.10.1
release     : 5
source      :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-menus/3.10/gnome-menus-3.10.1.tar.xz : 46950aba274c1ad58234374fa9b235258650737307f3bc396af48eb983668a71
license     :
    - GPL-2.0
summary     : GNOME library to access and manipulate menus
description : |
    GNOME library to access and manipulate menus
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-hide-System-Settings-category-from-menu-listi.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
