name       : libgnome-menus
version    : 3.36.0
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-menus/3.36/gnome-menus-3.36.0.tar.xz : d9348f38bde956fc32753b28c1cde19c175bfdbf1f4d5b06003b3aa09153bb1f
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME library to access and manipulate menus
description: |
    GNOME library to access and manipulate menus
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-hide-System-Settings-category.patch
    %patch -p1 < $pkgfiles/80_file_monitor_delayed.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc

    # Ensure legacy "applications.menu" can be found too
    ln -s /usr/share/xdg/menus/gnome-applications.menu $installdir/usr/share/xdg/menus/applications.menu
